### ISSUE TITLE
Issue happens when building proj Cannot find module 'acorn'

### ISSUE THREAD

**Issue by betimer** [InfoSec812/npm-audit-ci-wrapper#7]
module.js:538
    throw err;
    ^

Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\Go Agent\proj\node_modules\acorn-dynamic-import\lib\index.js:18:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! Test failed.  See above for more details.

**Comment by InfoSec812** [comment]
More information please. I cannot help you if you do not tell me the context.

**Comment by betimer** [comment]
@InfoSec812 Thanks for checking, I found that this is not an issue anymore. I will close this one, thanks.
